### ISSUE TITLE
Funktionale Erweiterung des RepairPickup

### ISSUE THREAD

**Issue by Horschde** [Achimobil/FS22_RepairPickup#2]
Guten Tag Achim,

wie in YT schon erwähnt, hier im Github mal der Vorschlag der Funktionserweiterung des Pickups.
Wie wäre es, wenn Du in den Pickup einen Hochdruckreiniger mit installierst. Der Service-Techniker wird es Dir danken, wenn er auf dem Feld ankommt und das zu wartende Fahrzeug erstmal grob vom Schmutz befreien kann, um seine Wartungsarbeiten durchzuführen.
Außerdem wäre es eine Erleichterung, wenn man mühevoll, z.B. einen Drehschemel Anhänger, rückwärts eingeparkt hat und anschließend merkt "Ich habe vergessen den vorm Einparken zu waschen"! ;-P

Grüße vom Horschd

**Comment by Achimobil** [comment]
Im 22er gibt es keine Features mehr. Deshalb close ich das hier
